spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE.ENDPOINT_URL.prod}:5432/postgres?currentSchema=${DATABASE.NAME.prod}
    username: ${DATABASE.USERNAME.prod}
    password: ${DATABASE.PASSWORD.prod}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        auto_quote_keyword: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO.CLIENT_ID}
            redirect-uri: ${KAKAO.REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao
            client-secret: ${KAKAO.CLIENT_SECRET}
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org.hibernate.SQL: debug
  slack:
    webhook_url: ${SLACK.WEBHOOK_URL.prod}
    config: classpath:logback-spring.xml

jwt:
  secret: ${JWT.SECRET}
  KAKAO_URL: https://kapi.kakao.com/v2/user/me
  APPLE_URL: https://appleid.apple.com/auth/keys
  ACCESS_TOKEN_EXPIRED: 7200000
  REFRESH_TOKEN_EXPIRED: 1209600000

softie:
  cron:
    init:
      routine: "0 0 0 * * *"