spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE.ENDPOINT_URL.prod}:5432/postgres?currentSchema=${DATABASE.NAME.prod}
    username: ${DATABASE.USERNAME.prod}
    password: ${DATABASE.PASSWORD.prod}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        auto_quote_keyword: true

logging:
  level:
    org.hibernate.SQL: debug
  slack:
    webhook_url: ${SLACK.WEBHOOK_URL.prod}
    config: classpath:logback-spring.xml
  webhook_url:
    sign_up: ${WEBHOOK_LOGGER_URL.SIGN_UP}
    withdraw: ${WEBHOOK_LOGGER_URL.WITHDRAW}
    error: ${WEBHOOK_LOGGER_URL.ERROR}

jwt:
  secret: ${JWT.SECRET}
  KAKAO_URL: https://kapi.kakao.com/v2/user/me
  APPLE_URL: https://appleid.apple.com/auth/keys
  ACCESS_TOKEN_EXPIRED: 7200000
  REFRESH_TOKEN_EXPIRED: 1209600000

batch:
  cron:
    init:
      routine: "0 0 0 * * *"

fcm:
  file_path: softie-server-fcm.json
  url: https://fcm.googleapis.com/v1/projects/${FCM.PROJECT_ID}/messages:send
  google_api: https://www.googleapis.com/auth/cloud-platform
  project_id: ${FCM.PROJECT_ID}

admin:
  username: ${ADMIN.USERNAME}
  password: ${ADMIN.PASSWORD}
